### ISSUE TITLE
Request for sisfall dataset

### ISSUE THREAD

**Issue by sylchw** [naomikgrant/SisFall_DL#1]
Hi there,

May I ask if you still have an archive of the sisfall dataset? It seems that the public link is broken.

Thank you!

- Sylvester

**Comment by naomikgrant** [comment]
Hi Sylvester,

So sorry you ran into that issue. I should have an archive of the Sisfall
dataset on my other laptop. I’ll try to place a download link on my GitHub.
Otherwise, you could also try to contact the authors here: https://www.mdpi.com/1424-8220/17/1/198

If you have any other questions, feel free to ask!

Kind regards,

Naomi Grant

**Comment by sylchw** [comment]
Thanks Naomi, appreciate it!

**Comment by farazBhatti** [comment]
here is the link for sisfall dataset : https://www.kaggle.com/datasets/nvnikhil0001/sis-fall-original-dataset/code
@sylchw
